<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction

Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones.

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage.

Therefore if we can determine if the first stage will land, we can determine the cost of a launch.

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

<a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01" target="_blank">Spacex DataSet</a>

**Navigate to the Go to UI screen**

*   Refer to this insruction in this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sign%20up%20for%20IBM%20Cloud%20-%20Create%20Db2%20service%20instance%20-%20Get%20started%20with%20the%20Db2%20console/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01">link</a> for viewing  the   Go to UI screen.

*   Later click on **Data link(below SQL)**  in the Go to UI screen  and click on **Load Data** tab.

*   Later browse for the downloaded spacex file.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/browsefile.png" width="800"/>

*   Once done select the schema andload the file.

 <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload3.png" width="800"/>

In [1]:
# !poetry add sqlalchemy==1.3.9
# !poetry add ibm_db_sa
# !poetry add ipython-sql
# # !pip install sqlalchemy==1.3.9
# # !pip install ibm_db_sa
# # !pip install ipython-sql

zsh:1: command not found: poetry
zsh:1: command not found: poetry
zsh:1: command not found: poetry

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [3]:
# %load_ext sql

**DB2 magic in case of old UI service credentials.**

In the next cell enter your db2 connection string. Recall you created Service Credentials for your Db2 instance before. From the **uri** field of your Db2 service credentials copy everything after db2:// (except the double quote at the end) and paste it in the cell below after ibm_db_sa://

<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_edX/images/URI.jpg">

in the following format

**%sql ibm_db_sa://my-username:my-password\@my-hostname:my-port/my-db-name**

**DB2 magic in case of new UI service credentials.**

<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/servicecredentials.png" width=600>  

*   Use the following format.

*   Add security=SSL at the end

**%sql ibm_db_sa://my-username:my-password\@my-hostname:my-port/my-db-name?security=SSL**

In [ ]:
# %sql ibm_db_sa://

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(filepath_or_buffer="datasets/datasets_sql.csv")
df.head()

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing _Outcome
0,04-06-2010,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,08-12-2010,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,22-05-2012,07:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,08-10-2012,00:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,01-03-2013,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

### Task 1

##### Display the names of the unique launch sites  in the space mission

In [9]:
df.loc[:,"Launch_Site"].value_counts().index

Index(['CCAFS SLC-40', 'CCAFS LC-40', 'KSC LC-39A', 'VAFB SLC-4E'], dtype='object')

### Task 2

##### Display 5 records where launch sites begin with the string 'CCA'

In [10]:
import re

In [24]:
def find_CCA(site):
	if re.search(pattern=r'^CCA', string=site) != None:
		return True
	return False

df.loc[df.loc[:,"Launch_Site"].apply(find_CCA)].head()

,Date,Time (UTC),Booster_Version,Launch_Site,Payload,PAYLOAD_MASS__KG_,Orbit,Customer,Mission_Outcome,Landing _Outcome
0,04-06-2010,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0,LEO,SpaceX,Success,Failure (parachute)
1,08-12-2010,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel of...",0,LEO (ISS),NASA (COTS) NRO,Success,Failure (parachute)
2,22-05-2012,07:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2,525,LEO (ISS),NASA (COTS),Success,No attempt
3,08-10-2012,00:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500,LEO (ISS),NASA (CRS),Success,No attempt
4,01-03-2013,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677,LEO (ISS),NASA (CRS),Success,No attempt

### Task 3

##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [28]:
def from_NASA(client):
	if re.search(pattern=r'^NASA', string=client) != None:
		return True
	return False

df.loc[df.loc[:,"Customer"].apply(from_NASA),"PAYLOAD_MASS__KG_"].sum()

99980

### Task 4

##### Display average payload mass carried by booster version F9 v1.1

In [30]:
def boosterModel(booster):
	if re.search(pattern=r'^F9 v1.1', string=booster) != None:
		return True
	return False

df.loc[df.loc[:,"Booster_Version"].apply(boosterModel),"PAYLOAD_MASS__KG_"].mean()

2534.6666666666665

### Task 5

##### List the date when the first successful landing outcome in ground pad was acheived.

*Hint:Use min function*

In [39]:
df.Date = pd.to_datetime(arg=df.Date, dayfirst=True)

In [81]:
def landingSuccess(landing):
	if re.search(pattern=r'Success', string=landing) != None:
		return True
	return False

df.loc[df.loc[:,"Landing _Outcome"].apply(landingSuccess),:].sort_values(by="Date", axis=0).loc[:,"Date"].head(1)

19   2015-12-22
Name: Date, dtype: datetime64[ns]

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [60]:
df_4000_6000 = df[df.loc[:,"PAYLOAD_MASS__KG_"].between(left=4000, right=6000)]
result = df_4000_6000[df_4000_6000.loc[:,"Mission_Outcome"].str.contains(pat=r'Success')].loc[:,"Booster_Version"].values
print(result)

['F9 v1.1' 'F9 v1.1 B1011' 'F9 v1.1 B1014' 'F9 v1.1 B1016' 'F9 FT B1020'
 'F9 FT B1022' 'F9 FT B1026' 'F9 FT B1030' 'F9 FT  B1021.2'
 'F9 FT B1032.1' 'F9 B4 B1040.1' 'F9 FT  B1031.2' 'F9 B4 B1043.1'
 'F9 FT  B1032.2' 'F9 B4  B1040.2' 'F9 B5 B1046.2' 'F9 B5 B1047.2'
 'F9 B5 B1046.3' 'F9 B5B1054' 'F9 B5 B1048.3' 'F9 B5 B1051.2 '
 'F9 B5B1060.1' 'F9 B5 B1058.2 ' 'F9 B5B1062.1']

### Task 7

##### List the total number of successful and failure mission outcomes

In [63]:
df.loc[:,"Mission_Outcome"].str.contains(pat=r"Success").value_counts()

True     100
False      1
Name: Mission_Outcome, dtype: int64

### Task 8

##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [67]:
maxLoad = df.loc[:,"PAYLOAD_MASS__KG_"].max()
df.loc[df.loc[:,"PAYLOAD_MASS__KG_"] == maxLoad, :].loc[:,"Booster_Version"]

74     F9 B5 B1048.4
77     F9 B5 B1049.4
79     F9 B5 B1051.3
80     F9 B5 B1056.4
82     F9 B5 B1048.5
83     F9 B5 B1051.4
85     F9 B5 B1049.5
92    F9 B5 B1060.2
93    F9 B5 B1058.3
94     F9 B5 B1051.6
95     F9 B5 B1060.3
99    F9 B5 B1049.7
Name: Booster_Version, dtype: object

### Task 9

##### List the failed landing_outcomes in drone ship, their booster versions, and launch site names for in year 2015

In [82]:
droneShip = df.loc[:,"Landing _Outcome"].str.contains(pat=r"drone")
after2015 = df.loc[:,"Date"].dt.year >= 2015
df.loc[droneShip & after2015, ["Landing _Outcome", "Booster_Version", "Launch_Site"]]

          Landing _Outcome Booster_Version   Launch_Site
13    Failure (drone ship)   F9 v1.1 B1012   CCAFS LC-40
16    Failure (drone ship)   F9 v1.1 B1015   CCAFS LC-40
18  Precluded (drone ship)   F9 v1.1 B1018   CCAFS LC-40
20    Failure (drone ship)   F9 v1.1 B1017   VAFB SLC-4E
21    Failure (drone ship)     F9 FT B1020   CCAFS LC-40
22    Success (drone ship)   F9 FT B1021.1   CCAFS LC-40
23    Success (drone ship)     F9 FT B1022   CCAFS LC-40
24    Success (drone ship)   F9 FT B1023.1   CCAFS LC-40
25    Failure (drone ship)     F9 FT B1024   CCAFS LC-40
27    Success (drone ship)     F9 FT B1026   CCAFS LC-40
28    Success (drone ship)   F9 FT B1029.1   VAFB SLC-4E
31    Success (drone ship)  F9 FT  B1021.2    KSC LC-39A
35    Success (drone ship)  F9 FT  B1029.2    KSC LC-39A
36    Success (drone ship)   F9 FT B1036.1   VAFB SLC-4E
39    Success (drone ship)   F9 FT B1038.1   VAFB SLC-4E
41    Success (drone ship)   F9 B4 B1041.1   VAFB SLC-4E
42    Success (drone ship)  F9 FT  B1031.2    KSC LC-39A
43    Success (drone ship)   F9 B4 B1042.1    KSC LC-39A
52    Success (drone ship)   F9 B4 B1045.1  CCAFS SLC-40
53    Success (drone ship)  F9 B5  B1046.1    KSC LC-39A

### Task 10

##### Rank the count of landing outcomes (such as Failure (drone ship) or Success (ground pad)) between the date 2010-06-04 and 2017-03-20, in descending order

In [97]:
# df.loc[:,"Date"].dt.year.between().loc[:,"Landing _Outcome"].value_counts(ascending=False)
condition_1 = df.loc[:,"Date"] > "2010-06-04" 
condition_2 = df.loc[:,"Date"] < "2017-03-20"
df.loc[condition_1 & condition_2].loc[:,"Landing _Outcome"].value_counts(ascending=False)

No attempt                10
Failure (drone ship)       5
Success (drone ship)       5
Controlled (ocean)         3
Success (ground pad)       3
Uncontrolled (ocean)       2
Failure (parachute)        1
Precluded (drone ship)     1
Name: Landing _Outcome, dtype: int64

### Reference Links

*   <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01&origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>

*   <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01&origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*   <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01&origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*   <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2022-01-01">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log

| Date       | Version | Changed by    | Change Description        |
| ---------- | ------- | ------------- | ------------------------- |
| 2021-10-12 | 0.4     | Lakshmi Holla | Changed markdown          |
| 2021-08-24 | 0.3     | Lakshmi Holla | Added library update      |
| 2021-07-09 | 0.2     | Lakshmi Holla | Changes made in magic sql |
| 2021-05-20 | 0.1     | Lakshmi Holla | Created Initial Version   |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>