<center>
    <img src="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/Logos/organization_logo/organization_logo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

<h1 align=center><font size = 5>Assignment: Notebook for Peer Assignment</font></h1>

# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:
[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the links below to download and save the datasets (.CSV files):

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Census Data</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Public Schools</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01" target="_blank">Chicago Crime Data</a>

**NOTE:** Ensure you have downloaded the datasets using the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be loaded into SQLite DB.
We will create three tables in as under:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

Let us now load the ipython-sql  extension and establish a connection with the database

*   Here you will be loading the csv files into the pandas Dataframe and then loading the data into the above mentioned sqlite tables.

*   Next you will be connecting to the sqlite database  **FinalDB**.

Refer to the previous lab for hints .

<a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing_SQLite.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2022-01-01">Hands-on Lab: Analyzing a real World Data Set</a>

In [5]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [6]:
import csv, sqlite3
con = sqlite3.connect("FinalDB.db")
cur = con.cursor()

In [7]:
import pandas as pd

# df = pd.read_csv("/Users/sylvain/IBM-Data-Science-Professional-Certificate/Course 4/Data sets/ChicagoCensusData.csv")
# df.to_sql("CensusData", con, if_exists="replace")

# df = pd.read_csv("/Users/sylvain/IBM-Data-Science-Professional-Certificate/Course 4/Data sets/ChicagoCrimeData.csv")
# df.to_sql("CrimeData", con, if_exists="replace")

# df = pd.read_csv("/Users/sylvain/IBM-Data-Science-Professional-Certificate/Course 4/Data sets/ChicagoPublicSchools.csv")
# df.to_sql("ChicagoPublicSchool", con, if_exists="replace")

In [8]:
%sql sqlite:///FinalDB.db

In [9]:
%sql alter table School rename to SchoolData

%sql select name from sqlite_master

 * sqlite:///FinalDB.db
(sqlite3.OperationalError) no such table: School
[SQL: alter table School rename to SchoolData]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
 * sqlite:///FinalDB.db
Done.

[('SchoolData',),
 ('ix_ChicagoPublicSchool_index',),
 ('CensusData',),
 ('ix_CensusData_index',),
 ('CrimeData',),
 ('ix_CrimeData_index',),
 ('ChicagoPublicSchool',)]

In [21]:
%sql select * from CrimeData order by WARD DESC limit 1;

 * sqlite:///FinalDB.db
Done.

[(72, 10102551, 'HY291329', '2015-06-06', '028XX W DEVON AVE', '860', 'THEFT', 'RETAIL THEFT', 'DRUG STORE', 0, 0, 2413, 24, 50.0, 2.0, '6', 1156278.0, 1942331.0, 2015, 41.9975448, -87.70046744, '(41.997544797, -87.700467444)')]

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [11]:
%sql select count(*) from CrimeData;

 * sqlite:///FinalDB.db
Done.

[(533,)]

### Problem 2

##### List community areas with per capita income less than 11000.

In [12]:
%sql select COMMUNITY_AREA_NAME, PER_CAPITA_INCOME from CensusData \
	where PER_CAPITA_INCOME < 11000;

 * sqlite:///FinalDB.db
Done.

[('West Garfield Park', 10934),
 ('South Lawndale', 10402),
 ('Fuller Park', 10432),
 ('Riverdale', 8201)]

### Problem 3

##### List all case numbers for crimes  involving minors?(children are not considered minors for the purposes of crime analysis)

In [13]:
%%sql 
select CASE_NUMBER 
from CrimeData 
where DESCRIPTION like "%MINOR%";

 * sqlite:///FinalDB.db
Done.

[('HL266884',), ('HK238408',)]

### Problem 4

##### List all kidnapping crimes involving a child?

In [22]:
%%sql 
select CASE_NUMBER 
from CrimeData 
where PRIMARY_TYPE = "KIDNAPPING" and DESCRIPTION like "%CHILD%";

 * sqlite:///FinalDB.db
Done.

[('HN144152',)]

### Problem 5

##### What kinds of crimes were recorded at schools?

In [26]:
%sql select distinct PRIMARY_TYPE as CRIME_TYPE_AT_SCHOOL from CrimeData \
	where LOCATION_DESCRIPTION like "%SCHOOL%";

 * sqlite:///FinalDB.db
Done.

[('BATTERY',),
 ('CRIMINAL DAMAGE',),
 ('NARCOTICS',),
 ('ASSAULT',),
 ('CRIMINAL TRESPASS',),
 ('PUBLIC PEACE VIOLATION',)]

### Problem 6

##### List the average safety score for each type of school.

In [16]:
%sql select "Elementary, Middle, or High School", round(avg(SAFETY_SCORE)) \
	from SchoolData\
	group by "Elementary, Middle, or High School";

 * sqlite:///FinalDB.db
Done.

[('ES', 50.0), ('HS', 50.0), ('MS', 48.0)]

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [17]:
%sql select COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY from CensusData order by PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC limit 5;

 * sqlite:///FinalDB.db
Done.

[('Riverdale', 56.5),
 ('Fuller Park', 51.2),
 ('Englewood', 46.6),
 ('North Lawndale', 43.1),
 ('East Garfield Park', 42.4)]

### Problem 8

##### Which community area is most crime prone?

In [18]:
sql_statement = """
	select COMMUNITY_AREA_NUMBER, count(*) as COUNT from CrimeData
	group by COMMUNITY_AREA_NUMBER
	order by COUNT DESC
	limit 1;
"""

com_area_number = cur.execute(sql_statement).fetchall()[0][0]

print(f"The community area (number) which is more crime prone is: {com_area_number}")

The community area (number) which is more crime prone is: 25.0

In [31]:
%%sql
select COMMUNITY_AREA_NUMBER
from CrimeData
group by COMMUNITY_AREA_NUMBER
order by count(*) desc  
limit 1;

 * sqlite:///FinalDB.db
Done.

[(25.0,)]

Double-click **here** for a hint

<!--
Query for the 'community area number' that is most crime prone.
-->

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

In [19]:
%%sql

select COMMUNITY_AREA_NAME from CensusData
where HARDSHIP_INDEX = (select max(HARDSHIP_INDEX) from CensusData);

 * sqlite:///FinalDB.db
Done.

[('Riverdale',)]

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

In [20]:
%%sql 

select CrimeData.COMMUNITY_AREA_NUMBER, count(CrimeData.COMMUNITY_AREA_NUMBER) as NUMBER_OF_CRIME, CensusData.COMMUNITY_AREA_NAME 
from CrimeData 
Inner join CensusData
on CrimeData.COMMUNITY_AREA_NUMBER = CensusData.COMMUNITY_AREA_NUMBER
group by CrimeData.COMMUNITY_AREA_NUMBER
order by NUMBER_OF_CRIME DESC
limit 1;

 * sqlite:///FinalDB.db
Done.

[(25.0, 43, 'Austin')]

In [33]:
%%sql 
select COMMUNITY_AREA_NAME 
from CensusData
where COMMUNITY_AREA_NUMBER = (
	select COMMUNITY_AREA_NUMBER
	from CrimeData
	group by COMMUNITY_AREA_NUMBER
	order by count(*) desc  
	limit 1	
)

 * sqlite:///FinalDB.db
Done.

[('Austin',)]

Copyright © 2020 This notebook and its source code are released under the terms of the [MIT License](https://bigdatauniversity.com/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).

## Author(s)

<h4> Hima Vasudevan </h4>
<h4> Rav Ahuja </h4>
<h4> Ramesh Sannreddy </h4>

## Contribtuor(s)

<h4> Malika Singla </h4>

## Change log

| Date       | Version | Changed by        | Change Description                             |
| ---------- | ------- | ----------------- | ---------------------------------------------- |
| 2022-03-04 | 2.5     | Lakshmi Holla     | Changed markdown.                              |
| 2021-05-19 | 2.4     | Lakshmi Holla     | Updated the question                           |
| 2021-04-30 | 2.3     | Malika Singla     | Updated the libraries                          |
| 2021-01-15 | 2.2     | Rav Ahuja         | Removed problem 11 and fixed changelog         |
| 2020-11-25 | 2.1     | Ramesh Sannareddy | Updated the problem statements, and datasets   |
| 2020-09-05 | 2.0     | Malika Singla     | Moved lab to course repo in GitLab             |
| 2018-07-18 | 1.0     | Rav Ahuja         | Several updates including loading instructions |
| 2018-05-04 | 0.1     | Hima Vasudevan    | Created initial version                        |

## <h3 align="center"> © IBM Corporation 2020. All rights reserved. <h3/>